ATTR_STOP_ID = "Stop ID"
ATTR_DIRECTION_ID = "Direction"
ATTR_NAME = "name"
ATTR_ROUTE_ID = "Route"
ATTR_DUE_IN = "Due in"
ATTR_DUE_AT = "Due at"
ATTR_OCCUPANCY = "Occupancy"
ATTR_NEXT_UP = "Next Arrival"
ATTR_NEXT_UP_DUE_IN = "Next Arrival due in"
ATTR_NEXT_OCCUPANCY = "Next Arrival occupancy"
ATTR_NEXT_ARRIVAL_LIST = "Next Arrivals"

CONF_SOURCE_HEADERS = "headers"
CONF_SOURCE_QUERY_PARAMS = "query_params"

CONF_STOP_ID = "stopid"
CONF_DIRECTION_ID = "directionid"
CONF_ROUTE = "route"
CONF_DEPARTURES = "departures"

CONF_SOURCES = "sources"
CONF_SOURCE_TIMEZONE = "timezone"
CONF_SOURCE = "source"
CONF_SOURCE_TRIP_UPDATES_URL = "trip_updates_url"
CONF_SOURCE_VEHICLE_POSITIONS_URL = "vehicle_positions_url"
CONF_SOURCE_ALERTS_URL = "alerts_url"
CONF_SOURCE_STATIC_URL = "static_url"
CONF_SOURCE_STATIC_PATH = "static_path"
DOMAIN = "gtfs_rt"

TIME_STR_FORMAT = "%I:%M:%S%p"
